logging:  level:    root: WARN    '[com.trilobyte.superheros]': DEBUG   

server:
  port: 8083
spring:
  application:
    name: superheros-api    version: '@project.version@'
  messages:
    basename: messages.messages
  datasource:
    url: jdbc:h2:mem:superherodb
    username: sa
    password: sa
  jpa:
    database: H2    open-in-view: false
    show-sql: true    hibernate:      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migrationspringfox:  documentation:    enabled: truemanagement:  endpoint:    health:      enabled: true      show-details: always  endpoints:    web:      exposure:        include: '*'